* Integrity
Definition of integrity
1:  firm adherence to a code of especially moral or artistic values :  incorruptibility
2:  an unimpaired condition :  soundness
3:  the quality or state of being complete or undivided :  completeness

Today I'll be using the first definition, incorruptibility. I'm hoping that this will start a productive conversation. Some of this will be a rehash of a previous post. I never finished that post because I was afraid of how people might react to it. I guess I didn't want to rock the boat. I'm going to try and not douse the field in gasoline and set it on fire. Only time will tell if I achieve that.

** Family
One of the reasons I've stayed at Jive was because of how they treated us. I feel like Jive used a higher standard than many companies to determine how to treat employees. They treated us like family. This can be seen by how many posts and conversations by Elisa, Ofer, Bryan, Robert and the rest of our leadership reference the "Jive Family". Seriously go search Brewspace for it. That feeling is what kept me here and is why I feel betrayed.
*** Times are tough
I want you to picture a family sitting down for dinner together. Idly chatting about their day, what the kids are learning in school, possibly some gossip about friends at school and how work is going for the parents. Red, the father, begins talking about how things have been tight lately. Work has been slow at the plant and they've cut hours back. Red then looks at Eric and say "Eric, it's time for you to go out and start a new life. These changes are tough, but essential. Know that I, along with your mother, are focused on creating a family that makes your sister, you and your children proud. We'll give you a few weeks of money to live off of, but we need you out by the end of the week". It doesn't matter what Red tells Eric, it's going to hurt. It doesn't matter what Red tells Laurie, she's going to worry that if things don't get better, she'll soon be out on the streets with her brother and a few dollars to get by.

*** Adoption
A year later Red is sitting down with Kitty and Laurie to dinner. Red looks at Laurie and says "You know, we've done ok since we got rid of your brother. We aren't doing as well as I'd hoped though. So your mom and I adopted you out to a nice family across town. They have money and are well educated. You'll have housekeepers, butlers, nannies and your own private tutors. The best part is you won't have to worry about us. They are paying us a fortune to take you off our hands". Sounds pretty great doesn't it? I mean who wouldn't applaud a father/mother team like that? /sarcasm

** It's business
If you're like me and believe some of the things that I believe, you'd find these scenarios to be crazy. You'd even say that Red was a bad parent, that he has no business having children and you'd be right. Yet here we are with our leaders doing the same thing. I know what the arguments is, "It's business. That's how business is done". If I'm frank, it's a bullshit excuse to transfer responsibility for bad decisions and bad behaviors. Our leadership had an opportunity to do things different, to be different. That's one of the compelling reasons I came to Jive, I felt like we did things different. While this feels like a betrayal to many of us, it wasn't the only one. 

*** No shared success
We've worked hard. I don't know anyone that's just phoned it in at Jive, leadership included. So when I see our leadership taking home millions of dollars to sell us off and at best we're getting only an additional year of vesting, I feel it's not equitable. We have leaders that have been here less time than some of the employees and they are getting 100% of their compensation package. If selling off Jive is considered being successful, then shouldn't we all be equally rewarded with our outstanding RSU's? If selling off Jive isn't considered a success, then why is leadership being rewarded for it? I don't recall ever getting a bonus or raise for not meeting my goals. 

** Why this matters
It matters because when you call people your family and then treat them this way, you're no longer adhering to a familial code. You're saying one thing and acting in a different manner. It demonstrates a lack of integrity. So don't call me family and don't say I'm your most important asset unless you mean it.

** Why I'm posting this now
I've wanted to write a similar post to this since the RIF's last year. I'd hoped that the RIF's would be a one time event and I'd never have to write this. I've looked at Aurea and I don't like what I see. I can find all kinds of reasons to not like my prospects for sticking around; my gut says I should run, the risk is too great, I don't agree with how they do business. 

I've been through a fair number of acquisitions in my career. I have never wanted to leave a company because of an acquisition, but this time it's different. The day it was announced I took a look at our soon to be owners and I wanted to run. 

I don't like the idea of training up my replacements for the next 6-9 months so I can be in the same position I'm in now. Aurea has a way of doing business that's made them very successful. They may be changing how they do business and I hope they are. For me, there is too much risk to stick around to see if they've really changed. 

I'm not faulting a company for making money. Heck, I like to make money myself. It's how you make the money that matters and I don't like how Aurea does it. I'm not saying Aurea employees are bad people, I'm sure they are generally very good people, but they do things that I consider to be bad. It's too early for me ot tell if Aurea has changed. They could go back to the same methods they've used in previous acquisitions with the very next company they acquire. They could even acquire that company under the Jive umbrella. I know how I felt during this transition and how people I care about at Jive felt. I would feel horrible knowing that I was supporting that and that I helped to contribute to that.

** For those reasons
I'm out. Wednesday the 21st will be my last day. I am going to miss this place. The people have been phenominal and I've come to care deeply about some of you. 

My hope with this post is to get people to think. I'm hoping that maybe we can look at how we've run businesses and make some changes. I hope that this post will leave the people that read it better than they were before they read it. 

If I can help in any way or if you want to grab coffee/lunch, please let me know. I wish you all love, happiness and prosperity.

Jayson Barley
503-757-1371
jayson.barley@gmail.com



