* Are your lights on?
** Who has the problem
** Don't solve other peoples problems when they can solve them perfectly well themselves
** If it's their problem, make it their problem
** If a person in a position to do something about a problem, but doesn't have the problem, then do something so he does
** If people really have their lights on, a little reminder may be more effective than your complicated solution
** What is the essense of your problem?
*** Don't take their solution method for a problem definition
*** If you solve their problem too readily, they'll never believe you solved their problem
*** Don't mistake a solution method for a problem definition, especially if it's your own solution method
*** You can never be sure you have a correct definition, even after the problem is solved
**** Don't ever stop trying to get a correct definition.
*** Don't leap to conclusions, but don't ignore your first impression
** How do we determine what is wrong
*** Each solution is the source of the next problem
*** The trickiest part of certain problems, is recognizing their existence
*** If you can't think of at least three things that might be wrong with your understanding of the problem, you don't understand the problem
*** Think of three reasons it won't work
** What can be done about the problem
** Test your definition on a foreigner, someone that's blind, a child or make  yourself foreign, blind or childlike
** Each viewpoint will produce a new misfit
** How can we change the problem statement to make the solution different
** What am I solving
*** Think of the most far out thing it could be
** Check to see that you haven't lost your way
** Check your meaning
** Once you have a problem statement in words, play with the words until the statement is in everyones head
*** Vary the stress patterns
*** Change positives to negatives and vice versa
*** Change may to must and must to may
*** Change or to either and either to or
*** Choose a term that is defined explicitly and use the explicit definition in place of it
*** For each etc and so forth and so on add one more explicit example to the list.
*** Search for persuasive words or phrases, such as obviously, therefore, clearly or certainly. Replace each word with the argument it is supposed to be replacing
*** Try to draw a picture of what some sentence or paragraph is saying
*** Express the words in the form of an equation
*** Express the equation in the form of words
*** Try to express in words what some picture is trying to say
*** Replace you with we and we with you
*** Replace we and you with both parties
*** Replace a with the and the with a
*** Replace some with every and every with some
*** Replace always with sometimes and sometimes with always
*** Replace sometime with never and never with sometime
** A problem is a difference between things as desired and things as perceived
*** Phantom problems are still real problems
** Where does the problem come from
** In the valley of the problem solvers, the problem creator is king or president or dean
** Who sent this problem
** What's he trying to do to me
** People seldom know what they want until you give them what they ask for
** Not too many people, really want their problems solved
** Do I really want a solution
** We never have enough time to consider whether we want it, but we always have enough time to regret it
** What is the problem
** What is a problem

Who has the problem
What is the problem
What can be done about the problem
