Imagine that your child is diagnosed with autism. As a parent I am sure you would have an overwhelming need to understand what caused it. Did you cause it? Could you have prevented it? In 1998 Andrew Wakefield published a study that indicated there was a link between children receiving the MMR vaccines and developing autism. This study gave many parents hope. They finally understood what was causing their children to be sick and what's even better, it could be prevented. If only it were that simple. I will show that the science behind this study was flawed. I will show that while it used testable ideas and involved the scientific community, it  did not rely on evidence.
* Uses testable ideas
The methodology used by Andrew was to study the history of 12 children that seemed to be developing normally then appeared to lose the skills they had developed. Various tests were run to help determine a potential cause for what we call autism. The evidence would indicate that two thirds of those children had received an MMR vaccine within days of the onset of symptoms. 
* Involves the scientific community
Scientists from around the world quickly began to try and replicate his findings. If this was true, it would be devastating. One of those studies was performed in Denmark and evaluated over half a million chidren of which about 700 had autism or autism like developments. Continued studies have shown no correlation between the development of autism and vaccinations. Just this year a new study, commisioned by a group of concerned parents that believe vaccines cause autism, could not demonstrate that vaccines cause autism. 
* Relies on evidence
It was later discovered that Andrew Wakefield had falsified his data. His research paper would be retracted and he would lose his medical license. Parents from around the world are putting their children at risk by not vaccinating them because of a study thatt was not based on any scientific evidence. 
* Leads to ongoing research
There is good that has come from this. Scientists have ruled out the MMR vaccine as a cause for autism. Research has continued to find a reason for autism. Once one is found, more research will be needed to understand why it causes autism. 

Science does work, when it is done in a scientific manner. You must be able to test the hypothesis, your conclusion must be backed by evidence and it must be peer reviewed. 

http://www.thelancet.com/journals/lancet/article/PIIS0140-6736(97)11096-0/abstract
http://www.nejm.org/doi/full/10.1056/NEJMoa021134
http://www.pnas.org/content/112/40/12498.full.pdf
